trainconfig:
  bs: 32
  lr: 0.00005
  max_epoch: 100

datasetconfig:
  masked_ratio: 0.3

bertconfig:
  max_age: 120
  max_visit_rank: 2048
  max_record_rank: 2048
  max_domain: 6
  hidden_size: 768
  num_hidden_layers: 12
  linear: True
  num_attention_heads: 12
  intermediate_size: 512

  